### ISSUE TITLE
12月2週目のTODO (12/7~12/12)

### ISSUE THREAD

**Issue by shosemaru** [shosemaru/TODO#3]

**Comment by shosemaru** [comment]
# 12/7のTODO
## TODO (10:00~10:30) 
- [ ] TODOの作成
  - [ ] タスク整理

##  産業医予約一覧 / レビュー最終修正  (10:30~12:30)
- [x] PR
  - [x] 環境設定
  - [x] 実装
  - [x] セルフレビュー

##  QA対応 / デザイン修正 (13:30~15:30)
- [x] PR
  - [x] 専門家に相談 / TOP
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3452
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3530
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3734
  - [x] サーベイ設定 / 一連
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3634
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3622
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3607
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3604
    - [x] https://github.com/FiNCDeveloper/wellness_survey/issues/3566
    - [ ] https://github.com/FiNCDeveloper/wellness_survey/issues/3307

##  産業医予約詳細 / フロント開発
- [x] PR
  - [x] 環境設定
  - [x] 実装
  - [x] セルフレビュー

## 残手持ちタスク
- [ ] [2.0h] サーベイ全体 / Hoverカラーの統一 https://github.com/FiNCDeveloper/wellness_survey/issues/3314 
- [ ] [2.0h] サーベイ全体 / Bodyカラーの統一 https://github.com/FiNCDeveloper/wellness_survey/issues/3559 
- [ ] サーベイ設定画面 / QA対応 
https://github.com/issues/assigned

**Comment by shosemaru** [comment]
- [ ] TODO更新
- [ ] Qiita投稿
- [ ] アメリカ登録
- [ ] JS勉強
- [ ] CSS設計勉強

**Comment by shosemaru** [comment]
# 12/7のTODO
## テーブル関連 / バグ対応 (10:30~11:00) 
- [x] PR
  - [x] 修正
  - [x] mergeされ次第報告

##  サイドバー / 色の訂正 (11:00~12:30)
- [x] PR
  - [x] 修正
  - [x] 影響範囲の確認

##  Fi-chat / CSS設計の計画練り (13:00~)
- [x] TODO/見積もりの作成

**Comment by shosemaru** [comment]
## 継続タスク
- [ ] A
- [ ] D
- [ ] T /
